In [1]:
import numpy as np
import pandas as pd
import os 
POSTGRES_PASSWORD = os.environ['POSTGRES_PASSWORD']
import psycopg2
from sqlalchemy import create_engine

In [2]:
bills=pd.read_csv('Data/bills.csv')              
commitees=pd.read_csv('Data/committees.csv')        
leadership=pd.read_csv('Data/leadership.csv')        
os_legislators=pd.read_csv('Data/os_legislators.csv')  
votingaffinity=pd.read_csv('Data/votingaffinity.csv')
comittee_members=pd.read_csv('Data/committee_members.csv')
congress_members=pd.read_csv('Data/congress_members.csv')
os_contributions=pd.read_csv('Data/os_contributions.csv')
terms=pd.read_csv('Data/terms.csv')

In [3]:
bills.columns = [x.lower() for x in bills.columns ] #make columns lowercase

In [4]:
bills.columns = [x.replace('.', '_') for x in bills.columns ] #replace periods with underscores

In [5]:
bills

,congress,introduceddate,number,title,type,url,latestaction_actiondate,latestaction_text,policyarea_name,amendmentnumber,latestaction,latestaction_actiontime
0,118,2023-10-04,405.0,A resolution expressing support for the design...,SRES,https://api.congress.gov/v3/bill/118/sres/405?...,2023-10-04,"Submitted in the Senate, considered, and agree...",Armed Forces and National Security,NaN,NaN,NaN
1,118,2023-09-29,2998.0,Land-Grant Research Equity and Accountability Act,S,https://api.congress.gov/v3/bill/118/s/2998?fo...,2023-09-29,Read twice and referred to the Committee on Ag...,Agriculture and Food,NaN,NaN,NaN
2,118,2023-09-27,373.0,A resolution designating the week of September...,SRES,https://api.congress.gov/v3/bill/118/sres/373?...,2023-09-27,"Submitted in the Senate, considered, and agree...",NaN,NaN,NaN,NaN
3,118,2023-09-27,2937.0,Increasing American Ferrosilicon Production Act,S,https://api.congress.gov/v3/bill/118/s/2937?fo...,2023-09-27,Read twice and referred to the Committee on Fi...,Foreign Trade and International Finance,NaN,NaN,NaN
4,118,2023-09-20,2874.0,Fresh Produce Procurement Reform Act of 2023,S,https://api.congress.gov/v3/bill/118/s/2874?fo...,2023-09-20,Read twice and referred to the Committee on Ag...,Agriculture and Food,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
38320,118,2023-02-15,443.0,Supply Chain Disruptions Relief Act,S,https://api.congress.gov/v3/bill/118/s/443?for...,2023-02-15,Read twice and referred to the Committee on Fi...,Taxation,NaN,NaN,NaN
38321,118,2023-02-14,413.0,Stock Buyback Accountability Act of 2023,S,https://api.congress.gov/v3/bill/118/s/413?for...,2023-02-14,Read twice and referred to the Committee on Fi...,Taxation,NaN,NaN,NaN
38322,118,2023-02-13,397.0,Promoting Physical Activity for Americans Act,S,https://api.congress.gov/v3/bill/118/s/397?for...,2023-02-13,Read twice and referred to the Committee on He...,Health,NaN,NaN,NaN
38323,118,2023-02-02,261.0,Protecting First Responders from Secondary Exp...,S,https://api.congress.gov/v3/bill/118/s/261?for...,2023-02-02,Read twice and referred to the Committee on th...,Crime and Law Enforcement,NaN,NaN,NaN
38324,118,2023-02-02,260.0,Promoting Access to Diabetic Shoes Act,S,https://api.congress.gov/v3/bill/118/s/260?for...,2023-02-02,Read twice and referred to the Committee on Fi...,Health,NaN,NaN,NaN

## Congress Members

In [6]:
congress_members.columns = [x.lower() for x in congress_members.columns ] #make columns lowercase
congress_members.columns = [x.replace('.', '_') for x in congress_members.columns ] #replace periods with underscores

In [7]:
congress_members.head(3).T

,0,1,2
bioguideid,B000944,C000127,C000141
birthyear,1952,1958,1943
currentmember,True,True,True
directordername,Sherrod Brown,Maria Cantwell,Benjamin L. Cardin
firstname,Sherrod,Maria,Ben
honorificname,Mr.,Ms.,Mr.
invertedordername,"Brown, Sherrod","Cantwell, Maria","Cardin, Benjamin L."
lastname,Brown,Cantwell,Cardin
officialwebsiteurl,https://www.brown.senate.gov/,https://www.cantwell.senate.gov,https://www.cardin.senate.gov/
partyhistory,"[{'partyAbbreviation': 'D', 'partyName': 'Demo...","[{'partyAbbreviation': 'D', 'partyName': 'Demo...","[{'partyAbbreviation': 'D', 'partyName': 'Demo..."
state,Ohio,Washington,Maryland
terms,"[{'chamber': 'House of Representatives', 'cong...","[{'chamber': 'House of Representatives', 'cong...","[{'chamber': 'House of Representatives', 'cong..."
updatedate,2023-04-01T12:42:12Z,2023-04-01T12:42:12Z,2023-04-01T12:42:13Z
addressinformation_city,Washington,Washington,Washington
addressinformation_district,DC,DC,DC
addressinformation_officeaddress,"503 Hart Senate Office Building Washington, DC...","511 Hart Senate Office Building Washington, DC...","509 Hart Senate Office Building Washington, DC..."
addressinformation_phonenumber,(202) 224-2315,(202) 224-3441,(202) 224-4524
addressinformation_zipcode,20515,20515,20515
cosponsoredlegislation_count,7873,3923,6100
cosponsoredlegislation_url,https://api.congress.gov/v3/member/B000944/cos...,https://api.congress.gov/v3/member/C000127/cos...,https://api.congress.gov/v3/member/C000141/cos...
depiction_attribution,"<a href=""http://www.senate.gov/artandhistory/h...","<a href=""http://www.senate.gov/artandhistory/h...","<a href=""http://www.senate.gov/artandhistory/h..."
depiction_imageurl,https://www.congress.gov/img/member/b000944_20...,https://www.congress.gov/img/member/c000127_20...,https://www.congress.gov/img/member/c000141_20...
sponsoredlegislation_count,1389.0,882.0,1265.0
sponsoredlegislation_url,https://api.congress.gov/v3/member/B000944/spo...,https://api.congress.gov/v3/member/C000127/spo...,https://api.congress.gov/v3/member/C000141/spo...
middlename,NaN,NaN,NaN
suffixname,NaN,NaN,NaN
nickname,NaN,NaN,NaN
leadership,NaN,NaN,NaN
district,NaN,NaN,NaN

In [8]:
congress_members = congress_members.drop(['terms', 'leadership', 'partyhistory'], axis = 1) #drop non-atomic variables that are contained elsewhere in other tables
congress_members

,bioguideid,birthyear,currentmember,directordername,firstname,honorificname,invertedordername,lastname,officialwebsiteurl,state,...,cosponsoredlegislation_count,cosponsoredlegislation_url,depiction_attribution,depiction_imageurl,sponsoredlegislation_count,sponsoredlegislation_url,middlename,suffixname,nickname,district
0,B000944,1952,True,Sherrod Brown,Sherrod,Mr.,"Brown, Sherrod",Brown,https://www.brown.senate.gov/,Ohio,...,7873,https://api.congress.gov/v3/member/B000944/cos...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b000944_20...,1389.0,https://api.congress.gov/v3/member/B000944/spo...,NaN,NaN,NaN,NaN
1,C000127,1958,True,Maria Cantwell,Maria,Ms.,"Cantwell, Maria",Cantwell,https://www.cantwell.senate.gov,Washington,...,3923,https://api.congress.gov/v3/member/C000127/cos...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/c000127_20...,882.0,https://api.congress.gov/v3/member/C000127/spo...,NaN,NaN,NaN,NaN
2,C000141,1943,True,Benjamin L. Cardin,Ben,Mr.,"Cardin, Benjamin L.",Cardin,https://www.cardin.senate.gov/,Maryland,...,6100,https://api.congress.gov/v3/member/C000141/cos...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/c000141_20...,1265.0,https://api.congress.gov/v3/member/C000141/spo...,NaN,NaN,NaN,NaN
3,C000174,1947,True,Thomas R. Carper,Thomas,Mr.,"Carper, Thomas R.",Carper,https://www.carper.senate.gov,Delaware,...,4476,https://api.congress.gov/v3/member/C000174/cos...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/c000174_20...,769.0,https://api.congress.gov/v3/member/C000174/spo...,R.,NaN,NaN,NaN
4,C001070,1960,True,Robert P. Casey Jr.,Bob,Mr.,"Casey, Robert P., Jr.",Casey,https://www.casey.senate.gov/,Pennsylvania,...,3922,https://api.congress.gov/v3/member/C001070/cos...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/c001070_20...,1180.0,https://api.congress.gov/v3/member/C001070/spo...,NaN,JR.,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,V000135,1969,True,Derrick Van Orden,Derrick,Mr.,"Van Orden, Derrick",Van Orden,https://vanorden.house.gov,Wisconsin,...,103,https://api.congress.gov/v3/member/V000135/cos...,Image courtesy of the Member,https://www.congress.gov/img/member/v000135_20...,14.0,https://api.congress.gov/v3/member/V000135/spo...,NaN,NaN,NaN,3.0
533,H001096,1962,True,Harriet M. Hageman,Harriet,NaN,"Hageman, Harriet M.",Hageman,https://hageman.house.gov,Wyoming,...,163,https://api.congress.gov/v3/member/H001096/cos...,Image courtesy of the Member,https://www.congress.gov/img/member/h001096_20...,28.0,https://api.congress.gov/v3/member/H001096/spo...,M.,NaN,NaN,NaN
534,R000618,1964,True,Pete Ricketts,Pete,Mr.,"Ricketts, Pete",Ricketts,https://www.ricketts.senate.gov,Nebraska,...,169,https://api.congress.gov/v3/member/R000618/cos...,Official U.S. Senate Photo,https://www.congress.gov/img/member/r000618_20...,17.0,https://api.congress.gov/v3/member/R000618/spo...,NaN,NaN,NaN,NaN
535,M001227,1972,True,Jennifer L. McClellan,Jennifer,NaN,"McClellan, Jennifer L.",McClellan,https://mcclellan.house.gov/,Virginia,...,209,https://api.congress.gov/v3/member/M001227/cos...,Image courtesy of the Member,https://www.congress.gov/img/member/m001227_20...,5.0,https://api.congress.gov/v3/member/M001227/spo...,L.,NaN,NaN,4.0
536,B001320,1979,True,Laphonza R. Butler,Laphonza,Ms.,"Butler, Laphonza R.",Butler,https://www.butler.senate.gov/,California,...,9,https://api.congress.gov/v3/member/B001320/cos...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Terms

In [9]:
terms.columns = [x.lower() for x in terms.columns ] #make columns lowercase
terms.columns = [x.replace('.', '_') for x in terms.columns ] #replace periods with underscores
terms.head(3).T

                  0        1        2
chamber      Senate   Senate   Senate
congress        107      108      109
endyear      2003.0   2005.0   2007.0
membertype  Senator  Senator  Senator
startyear      2002     2003     2005
statecode        TX       TX       TX
statename     Texas    Texas    Texas
bioguideid  C001056  C001056  C001056
district        NaN      NaN      NaN

## Leadership

In [10]:
leadership.columns = [x.lower() for x in leadership.columns ] #make columns lowercase
leadership.columns = [x.replace('.', '_') for x in leadership.columns ] #replace periods with underscores
leadership.head(3).T

,0,1,2
congress,113,114,115
type,Assistant Democratic Leader,Assistant Majority Leader,Majority Whip
bioguideid,C001056,C001056,C001056
current,NaN,NaN,NaN

## OS Legislators

In [11]:
os_legislators.columns = [x.lower() for x in os_legislators.columns ] #make columns lowercase
os_legislators.columns = [x.replace('.', '_') for x in os_legislators.columns ] #replace periods with underscores
os_legislators = os_legislators.drop_duplicates()
os_legislators.head(3).T

,0,1,2
cid,N00050780,N00035774,N00026050
firstl,Mary Peltola,Dan Sullivan,Lisa Murkowski
lastnam,Peltola,Sullivan,Murkowski
party,D,R,R
offic,AK01,AKS1,AKS2
gend,F,M,F
first_elected,2022,2014,2002
xit_cod,0,0,0
commen,NaN,NaN,NaN
phon,NaN,202-224-3004,202-224-6665
fax,NaN,NaN,202-224-5301
w,NaN,https://www.sullivan.senate.gov,https://www.murkowski.senate.gov
webform,NaN,https://www.sullivan.senate.gov/contact/email,https://www.murkowski.senate.gov/public/index....
congress_offic,NaN,702 Hart Senate Office Building,522 Hart Senate Office Building
oguide_id,NaN,S001198,M001153
votesmart_id,NaN,NaN,15841.0
feccandid,NaN,S4AK00214,S4AK00099
witter_id,NaN,SenDanSullivan,LisaMurkowski
youtube_url,NaN,NaN,https://youtube.com/senatormurkowski
facebook_id,NaN,SenDanSullivan,SenLisaMurkowski
hd,NaN,1964-11-13,1957-05-22

In [12]:
newbio = ['B001311','B001313','B001314','B001315','C001125',
          'C001126','C001127','C001129','E000071','F000475','G000061',
          'G000551','G000595','H001093','L000595','L000597','M000687',
          'M001210','M001217','M001227','R000579','R000618',
          'S001218','T000165','T000488','P000619']
legs = ['Dan Bishop','Shontel Brown','Aaron Bean','Nikki Budzinski',
        'Troy Carter','Mike Carey','Sheila Cherfilus-McCormick',
        'Mike Collins','Jake Ellzey','Brad Finstad','Mike Garcia',
        'Raul M Grijalva','Bob Good','Erin Houchin','Julia Letlow',
        'Laurel Lee','Kweisi Mfume','Greg Murphy','Jared Moskowitz',
        'Jennifer McClellan','Pat Ryan','Pete Ricketts','Melanie Stansbury',
        'Tom Tiffany','Shri Thanedar','Mary Peltola']
def replacebio(b,n):
    os_legislators.loc[os_legislators['firstl']==n, 'oguide_id'] = b
for b, n in zip(newbio, legs):
    replacebio(b,n)

In [21]:
os_legislators = os_legislators[['cid', 'party', 'oguide_id']]
os_legislators = os_legislators.rename(columns={"oguide_id": 'bioguideid'}) # can also do just the dictionary and axis = 1 to tell it I am renaming a column

In [22]:
os_legislators

           cid party bioguideid
0    N00050780     D    P000619
1    N00035774     R    S001198
2    N00026050     R    M001153
3    N00044245     R    C001054
4    N00041295     R    M001212
..         ...   ...        ...
532  N00032838     D    M001183
533  N00009771     R    C001047
534  N00049197     R    H001096
535  N00006236     R    B001261
536  N00029788     R    L000571

[536 rows x 3 columns]

In [26]:
members = pd.merge(congress_members, os_legislators,
                   left_on='bioguideid',
                   right_on='bioguideid',
                   how='outer',
                   validate='one_to_one', 
                  indicator = 'matched')

In [27]:
members

,bioguideid,birthyear,currentmember,directordername,firstname,honorificname,invertedordername,lastname,officialwebsiteurl,state,...,depiction_imageurl,sponsoredlegislation_count,sponsoredlegislation_url,middlename,suffixname,nickname,district,cid,party,matched
0,B000944,1952.0,True,Sherrod Brown,Sherrod,Mr.,"Brown, Sherrod",Brown,https://www.brown.senate.gov/,Ohio,...,https://www.congress.gov/img/member/b000944_20...,1389.0,https://api.congress.gov/v3/member/B000944/spo...,NaN,NaN,NaN,NaN,N00003535,D,both
1,C000127,1958.0,True,Maria Cantwell,Maria,Ms.,"Cantwell, Maria",Cantwell,https://www.cantwell.senate.gov,Washington,...,https://www.congress.gov/img/member/c000127_20...,882.0,https://api.congress.gov/v3/member/C000127/spo...,NaN,NaN,NaN,NaN,N00007836,D,both
2,C000141,1943.0,True,Benjamin L. Cardin,Ben,Mr.,"Cardin, Benjamin L.",Cardin,https://www.cardin.senate.gov/,Maryland,...,https://www.congress.gov/img/member/c000141_20...,1265.0,https://api.congress.gov/v3/member/C000141/spo...,NaN,NaN,NaN,NaN,N00001955,D,both
3,C000174,1947.0,True,Thomas R. Carper,Thomas,Mr.,"Carper, Thomas R.",Carper,https://www.carper.senate.gov,Delaware,...,https://www.congress.gov/img/member/c000174_20...,769.0,https://api.congress.gov/v3/member/C000174/spo...,R.,NaN,NaN,NaN,N00012508,D,both
4,C001070,1960.0,True,Robert P. Casey Jr.,Bob,Mr.,"Casey, Robert P., Jr.",Casey,https://www.casey.senate.gov/,Pennsylvania,...,https://www.congress.gov/img/member/c001070_20...,1180.0,https://api.congress.gov/v3/member/C001070/spo...,NaN,JR.,NaN,NaN,N00027503,D,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
538,F000062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N00007364,D,right_only
539,C001129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N00035370,R,right_only
540,S001197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N00035544,R,right_only
541,C001084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N00032019,D,right_only
542,S001192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N00033932,R,right_only

In [29]:
members = pd.merge(congress_members, os_legislators, 
                   on = 'bioguideid', 
                   how = 'inner')

## OS Contributions

In [31]:
os_contributions.columns = [x.lower() for x in os_contributions.columns ] #make columns lowercase
os_contributions.columns = [x.replace('.', '_') for x in os_contributions.columns ] #replace periods with underscores
os_contributions.head()

                          org_nam   otal   pac   ndiv        cid
0                 State of Alaska  19541     0  19541  N00050780
1         Sonosky, Chambers et al  16050     0  16050  N00050780
2       General Communication Inc  15150  2500  12650  N00050780
3                      Google Inc  14164     0  14164  N00050780
4  University of Alaska/Anchorage  13938     0  13938  N00050780

In [33]:
os_contributions = os_contributions.rename(columns = {'otal': 'total', 'org_nam': 'org_name'})
os_contributions

                                 org_name  total    pac   ndiv        cid
0                         State of Alaska  19541      0  19541  N00050780
1                 Sonosky, Chambers et al  16050      0  16050  N00050780
2               General Communication Inc  15150   2500  12650  N00050780
3                              Google Inc  14164      0  14164  N00050780
4          University of Alaska/Anchorage  13938      0  13938  N00050780
...                                   ...    ...    ...    ...        ...
1985  New York Cancer & Blood Specialists  15000      0  15000  N00038260
1986                      Transdigm Group  15000  10000   5000  N00038260
1987                         Altria Group  12900  10000   2900  N00038260
1988                            LHC Group  11800   5000   6800  N00038260
1989                       Brymak & Assoc  11600      0  11600  N00038260

[1990 rows x 5 columns]

## Comittees

In [34]:
commitees.columns = [x.lower() for x in commitees.columns ] #make columns lowercase
commitees.columns = [x.replace('.', '_') for x in commitees.columns ] #replace periods with underscores
commitees = commitees.drop(['subcommittees'], axis = 1) #drop nonatomic column
commitees.head()

,chamber,committeetypecode,name,systemcode,url,parent_name,parent_systemcode,parent_url
0,House,Other,Bicentenary Committee,hcza00,https://api.congress.gov/v3/committee/house/hc...,NaN,NaN,NaN
1,House,Standing,Energy (Ad Hoc) Committee,hhah00,https://api.congress.gov/v3/committee/house/hh...,NaN,NaN,NaN
2,House,Select,U.S. Role in Iranian Arms Committee,hlbz00,https://api.congress.gov/v3/committee/house/hl...,NaN,NaN,NaN
3,House,Select,"Children, Youth, and Families (Select) Committee",hlcf00,https://api.congress.gov/v3/committee/house/hl...,NaN,NaN,NaN
4,House,Select,Select Committee on the Climate Crisis,hlcn00,https://api.congress.gov/v3/committee/house/hl...,NaN,NaN,NaN

In [36]:
commitees['systemcode'] = [x[:-2].upper() for x in commitees['systemcode']] #remove last two characters of string and make it upper case

## Committee Members

In [37]:
comittee_members.columns = [x.lower() for x in comittee_members.columns ] #make columns lowercase
comittee_members.columns = [x.replace('.', '_') for x in comittee_members.columns ] #replace periods with underscores
comittee_members.head()

  committee_code  rank           title bioguide
0           HSII   1.0           Chair  W000821
1           HSII   1.0  Ranking Member  G000551
2           HSII   2.0             NaN  L000564
3           HSII   2.0             NaN  N000179
4           HSII   3.0             NaN  W000804

## Voting Affinity

In [38]:
votingaffinity

        icpsr  member_compare  affinity_score
0       14226           14435        0.305147
1       14226           14858        0.375000
2       14226           14871        0.352941
3       14226           14921        0.772059
4       14226           15015        0.356618
...       ...             ...             ...
204133  91980           31101        0.202532
204134  91980           31102        0.830018
204135  91980           31103        0.169982
204136  91980           39301        0.198915
204137  91980           39307        0.202532

[204138 rows x 3 columns]

## Create the Database

In [40]:
dbserver = psycopg2.connect(
    host = 'postgres',
    user = 'postgres', 
    password = POSTGRES_PASSWORD,
    port = 5432
)
dbserver.autocommit = True

In [41]:
cursor = dbserver.cursor()

In [42]:
try: 
    cursor.execute('CREATE DATABASE congress')
except:
    cursor.execute("DROP DATABASE congress")
    cursor.execute('CREATE DATABASE congress')

In [43]:
engine = create_engine('postgresql+psycopg2://{user}:{password}@{host}:{port}/{db}'.format(
    user = 'postgres', password = POSTGRES_PASSWORD, host = 'postgres', port = 5432, db = 'congress'
))

Need to upload: 
- members
- bills
- committees
- committee members
- terms
- leadership
- contributions

In [45]:
print(members.shape[0])
members.to_sql('members', con = engine, index = False, chunksize=1000, if_exists = 'replace')

530

530

In [49]:
print(bills.shape[0])
bills.to_sql('bills', con = engine, index = False, chunksize=500, if_exists = 'replace')

38325

38325

In [50]:
print(commitees.shape[0])
commitees.to_sql('committees', con = engine, index = False, chunksize=500, if_exists = 'replace')

714

714

In [52]:
print(comittee_members.shape[0])
comittee_members.to_sql('comittee_members', con = engine, index = False, chunksize=500, if_exists = 'replace')

3866

3866

In [53]:
print(terms.shape[0])
terms.to_sql('terms', con = engine, index = False, chunksize=500, if_exists = 'replace')

278

278

In [54]:
print(leadership.shape[0])
leadership.to_sql('leadership', con = engine, index = False, chunksize=500, if_exists = 'replace')

79

79

In [55]:
print(os_contributions.shape[0])
os_contributions.to_sql('contributions', con = engine, index = False, chunksize=500, if_exists = 'replace')

1990

1990